version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
    postgres: