services:
  postgres:
    image: postgres:17-alpine
    container_name: shutikate-database
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bridge_network

  prisma-migrate:
    build:
      context: .
      target: prisma-migrate
      dockerfile: Dockerfile
    container_name: shutikate-prisma-migrate
    restart: "no"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bridge_network

  library-app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: shutikate-app
    command: npm run start:dev
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - prisma-migrate
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - bridge_network

volumes:
    postgres-data:

networks:
  bridge_network:
    driver: bridge